"""RBAC/ReBAC-gated querying over REAL Phase-4 data (10-building baseline) with
REAL, persisted occupant roles -- 10 Deans, 100 Teachers, 390 Students (1 dean +
10 teachers + 39 students PER building), generated by build_campus_roles.py
into variants/rbac10/{occupant_roles.json,class_rosters.json,deans_by_building.json}.

Unlike query_user.py, this script does NOT accept a --caller-role/--target-role
flag at all: every principal's role (and home building) is looked up from that
persisted real registry, never asserted on the command line. An occupant not
in the registry has no role and every query about/from them is denied by
policy, exactly like a real access-control system would behave.

Two RBAC layers, both real:
  Layer 1 (infrastructure): security.authorize.authorize() -- is this a
    registered query client at all? (For a building: target this is the ONLY
    gate -- Q1/Q2 are building-wide, not about any one person, so the persona
    layer below never applies to them, exactly as query_engine.py's own Q1/Q2
    use target type "building" while Q3/Q5/Q6 use "occupant".)
  Layer 2 (persona ReBAC): security.campus_policy.evaluate_campus_query_policy()
    -- given both real roles AND real home buildings, what may this caller
    see about this target? Includes the Dean-only cross-building rule added
    to campus_policy.py alongside this script (register_occupant_building /
    the Rule 2b check): every other role is confined to its own building.

All 6 query types run against the REAL Phase-4 event log via query_engine.py's
QueryEngine (Q1, Q2, Q3, Q5, Q6) plus a TRACK (full historical trajectory)
capability built the same way -- no synthetic/toy scenario anywhere in this
script. Q3/Q5/TRACK are historical/trajectory queries and, matching the
existing rule already implemented in security/user_privacy_protocol.py,
require the caller to hold L4_HISTORICAL_TRACK outright (there is no partial
redaction of "did they visit all zones" the way there is for "where are they
right now").

    python query_campus_real.py --demo
    python query_campus_real.py --caller <id> --target <id> --query Q6 [--purpose ...] [--at-time HH:MM:SS]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT_DIR = HERE.parent
sys.path = [p for p in sys.path if p not in (str(HERE), str(ROOT_DIR))]
sys.path.insert(0, str(ROOT_DIR))
sys.path.insert(0, str(HERE))

from dsts.zones import zone_sector, zone_label                          # noqa: E402
from query_engine import QueryEngine                                     # noqa: E402
from security.authorize import (                                         # noqa: E402
    Role, authorize, get_audit_log, register_node, set_enforce_policy, clear_registry, clear_audit_log,
)
from security.campus_policy import (                                     # noqa: E402
    CampusRole, DisclosureLevel, QueryContext, QueryPurpose,
    check_office_presence, clear_campus_registry, evaluate_campus_query_policy,
    get_occupant_role, register_class_roster, register_occupant_building, register_occupant_role,
)

ROLES_DIR = HERE / "variants" / "rbac10"
DEFAULT_AT_TIME = "23:59:59"   # "as of end of day" -> most recent known detection
TRAJECTORY_QUERIES = {"Q3", "Q5", "TRACK"}   # require L4 outright, no partial redaction


def _real_sector(zone: str) -> str:
    return zone_sector("z_T" if zone == "zT" else zone)


def _real_label(zone: str) -> str:
    return zone_label("z_T" if zone == "zT" else zone)


def _confidence_band(p: float | None) -> str:
    if p is None:
        return "Unknown"
    if p >= 0.8:
        return "High (p>=0.8)"
    if p >= 0.5:
        return "Medium (p>=0.5)"
    return "Low (p<0.5)"


def load_real_registry() -> tuple[dict[str, str], dict[str, list[str]]]:
    roles = json.loads((ROLES_DIR / "occupant_roles.json").read_text())
    rosters = json.loads((ROLES_DIR / "class_rosters.json").read_text())
    if not roles:
        raise SystemExit("no roles found -- run: python build_campus_roles.py first")
    return roles, rosters


def register_real_registry(roles: dict[str, str], rosters: dict[str, list[str]], engine: QueryEngine) -> None:
    """Populate ALL real registries (role, roster, home building) from the
    persisted assignment files and the real per-building rosters loaded by
    the engine -- never from a caller's own claim."""
    for occupant_id, role_str in roles.items():
        register_occupant_role(occupant_id, role_str)
        register_node(occupant_id, Role.QUERY_CLIENT)   # Layer-1: every real occupant may act as a query client
    for teacher_id, student_ids in rosters.items():
        register_class_roster(teacher_id, student_ids)
    for building_id, occupant_ids in engine.registered.items():
        for occupant_id in occupant_ids:
            register_occupant_building(occupant_id, building_id)


def build_engine() -> QueryEngine:
    # enforce_rbac=False: Layer-1 checks are done explicitly below with the
    # REAL caller_id (query_engine's own class would otherwise re-register
    # every caller as QUERY_CLIENT and blur which layer denied what).
    return QueryEngine.from_paths(enforce_rbac=False)


def track_answer(engine: QueryEngine, target_id: str) -> dict:
    """Full real historical trajectory -- the L4/TRACK-only capability."""
    history = sorted((e for e in engine.events if e.occupant_id == target_id), key=lambda e: e.timestamp)
    if not history:
        return {"error": f"no real detections of {target_id} at all"}
    zone_counts: dict[str, int] = {}
    for e in history:
        zone_counts[e.zone] = zone_counts.get(e.zone, 0) + 1
    most_frequent = max(zone_counts, key=zone_counts.get)
    return {
        "total_detections": len(history),
        "distinct_zones_visited": sorted(zone_counts),
        "most_frequented_zone": f"{most_frequent} ({_real_label(most_frequent)}, {zone_counts[most_frequent]} visits)",
        "zone_visit_counts": zone_counts,
        "waypoints": [{"time": e.timestamp, "building": e.building, "zone": e.zone,
                      "zone_label": _real_label(e.zone), "probability": e.identity_probability}
                     for e in history],
    }


def q6_answer_for_disclosure(engine: QueryEngine, target_id: str, level: DisclosureLevel, at_time: str) -> dict:
    """Real Q6 (point-in-time location), redacted to match `level`."""
    current = engine.Q6(occupant_id=target_id, at_time=at_time)
    if not current.success:
        return {"error": f"no real detection of {target_id} at or before t={at_time}"}
    zone, building, ts, prob = (current.answer["zone"], current.answer["building"],
                               current.answer["time"], current.answer["identity_probability"])
    if level == DisclosureLevel.L1_PRESENCE:
        return check_office_presence(target_id, zone)
    if level == DisclosureLevel.L2_CURRENT_ZONE:
        return {"building": building, "sector": _real_sector(zone),
                "approx_time": ts[:2] + ":00:00" if len(ts) == 8 else ts, "confidence": _confidence_band(prob)}
    return {"building": building, "zone": zone, "zone_label": _real_label(zone), "time": ts, "probability": prob}


def get_real_role(occupant_id: str) -> str:
    role = get_occupant_role(occupant_id)
    return role.value if role else "UNASSIGNED"


def run_building_query(engine: QueryEngine, caller_id: str, q_type: str, building_id: str, **params) -> None:
    """Q1/Q2 -- building-wide queries. Infra-RBAC ONLY: there is no single
    target occupant for the persona layer to evaluate a relationship
    against, exactly matching query_engine.py's own Q1/Q2 using target type
    'building', not 'occupant'."""
    target_resource = f"building:{building_id}"
    print(f"\n{'=' * 78}\n{caller_id} -> {q_type} on {building_id}  params={params}")
    permitted = authorize(caller_id, "QUERY", target_resource)
    reason = get_audit_log()[-1]["reason"]
    print(f"  Layer 1 (infra RBAC): {'PERMIT' if permitted else 'DENY'}  (reason={reason or 'registered QUERY_CLIENT'})")
    print("  Layer 2 (persona ReBAC): N/A -- building-wide query, no target occupant")
    if not permitted:
        return
    if q_type == "Q1":
        res = engine.Q1(building_id=building_id, after_time=params["after_time"])
    else:
        res = engine.Q2(building_id=building_id, at_time=params["at_time"])
    print(f"  Query:  {res.query_text}")
    print(f"  Answer: {res.answer}")
    for line in res.evidence[:3]:
        print(f"   {line}")


def run_occupant_query(engine: QueryEngine, caller_id: str, target_id: str, q_type: str, *, purpose: str,
                       is_office_hours: bool, authorized_investigation: bool, at_time: str,
                       building_id: str | None = None, before_time: str | None = None) -> None:
    """Q3/Q5/Q6/TRACK -- queries about ONE target occupant. Both RBAC layers apply."""
    print(f"\n{'=' * 78}\n{caller_id} -> {q_type} on {target_id}  "
         f"(purpose={purpose}, office_hours={is_office_hours}, authorized={authorized_investigation})")

    target_resource = f"occupant:{target_id}"
    permitted = authorize(caller_id, "QUERY", target_resource)
    last_reason = get_audit_log()[-1]["reason"]
    if not permitted:
        print(f"  Layer 1 (infra RBAC) DENIED: {last_reason}")
        if last_reason.startswith("target_occupant_denied_by_policy"):
            print("  (^ a Layer-2 persona-policy denial surfacing through the Layer-1 check --"
                 " see the script docstring)")
        return
    print(f"  Layer 1 (infra RBAC):  PERMIT  (reason={last_reason or 'registered QUERY_CLIENT'})")

    caller_role, target_role = get_real_role(caller_id), get_real_role(target_id)
    print(f"  Real roles/buildings:  caller={caller_role}  target={target_role}")

    context = QueryContext(purpose=QueryPurpose.from_str(purpose), is_office_hours=is_office_hours,
                           authorized_investigation=authorized_investigation)
    decision = evaluate_campus_query_policy(caller_id, target_id, context=context, purpose=context.purpose)
    print(f"  Layer 2 (persona ReBAC): {'PERMIT' if decision.permitted else 'DENY'}  level={decision.level.name}")
    print(f"  Reason: {decision.reason}")

    if not decision.permitted or decision.level == DisclosureLevel.L0_NONE:
        return
    if q_type in TRAJECTORY_QUERIES and decision.level != DisclosureLevel.L4_HISTORICAL_TRACK:
        print(f"  DENIED (temporal scope): {q_type} is a trajectory query requiring L4_HISTORICAL_TRACK outright; "
             f"caller only holds {decision.level.name}")
        return

    if q_type == "Q6":
        print(f"  Query:  Where was {target_id} at t={at_time}?")
        print(f"  Disclosed ({decision.level.name}): {q6_answer_for_disclosure(engine, target_id, decision.level, at_time)}")
    elif q_type == "Q3":
        res = engine.Q3(occupant_id=target_id, building_id=building_id, before_time=before_time)
        print(f"  Query:  {res.query_text}")
        print(f"  Disclosed (L4_HISTORICAL_TRACK): answer={res.answer}  evidence={res.evidence}")
    elif q_type == "Q5":
        res = engine.Q5(occupant_id=target_id, building_id=building_id)
        print(f"  Query:  {res.query_text}")
        print(f"  Disclosed (L4_HISTORICAL_TRACK): answer={res.answer}  evidence={res.evidence}")
    elif q_type == "TRACK":
        print(f"  Query:  Full historical trajectory for {target_id}")
        print(f"  Disclosed (L4_HISTORICAL_TRACK): {track_answer(engine, target_id)}")


def print_role_capabilities() -> None:
    print(f"\n{'=' * 78}\nROLE CAPABILITIES (from security/campus_policy.py's actual matrix + rules)\n")
    print("DEAN")
    print("  CAN:  query ANY occupant in ANY building -- the only role exempt from the")
    print("        home-building restriction (Rule 2b in campus_policy.py).")
    print("  CAN:  get L4 (full historical track) on a Teacher/Student when purpose=")
    print("        security_investigation/audit with authorized_investigation=True.")
    print("  CAN:  get L2 (coarse current zone) on anyone for routine/general lookups.")
    print("  CANNOT: get L4 detail on a *routine* lookup -- capped to L2 without an")
    print("        explicit investigation/audit purpose (minimum-necessary-disclosure).")
    print("\nTEACHER")
    print("  CAN:  query Students, peer Teachers, and their Dean -- but ONLY within")
    print("        their OWN building (home-building restriction applies).")
    print("  CAN:  get L2 (coarse current zone) on any student in their building --")
    print("        roster membership only changes the audit-log wording, not the tier.")
    print("  CANNOT: query an occupant of a DIFFERENT building (Dean-only).")
    print("  CANNOT: get L4/historical (Q3, Q5, TRACK) on any student -- ceiling tops")
    print("        out at L2, and trajectory queries require L4 outright.")
    print("\nSTUDENT")
    print("  CAN:  get L1 (presence-only, e.g. 'Away from Cabin') on their own Teacher")
    print("        or Dean, during office hours, within their own building.")
    print("  CAN:  get full L4 on themselves (self-query exemption).")
    print("  CANNOT: query a peer Student at all -- hard L0 regardless of purpose")
    print("        (anti-stalking; the matrix ceiling for student->student is L0).")
    print("  CANNOT: query anyone once office hours end -- drops to L0.")
    print("  CANNOT: get anything beyond presence on Teacher/Dean -- never coarse zone")
    print("        or exact room, and never Q3/Q5/TRACK on anyone but themselves.")
    print("  CANNOT: query an occupant of a different building (same as Teacher).")


def run_demo() -> None:
    roles, rosters = load_real_registry()
    deans_by_building = json.loads((ROLES_DIR / "deans_by_building.json").read_text())
    engine = build_engine()
    register_real_registry(roles, rosters, engine)

    def students_in(building: str):
        return (o for o in engine.registered[building] if roles.get(o) == "student")

    # Per-building registry: 1 dean + 10 teachers + 39 students PER building
    # (10 deans + 100 teachers + 390 students = 500 total). Primary demo
    # building is building_5 -- its dean, 0001738, is the same real occupant
    # used in the earlier query_engine.py / demo_rbac_real.py examples.
    home_building = "building_5"
    dean_id = deans_by_building[home_building]
    teacher_ids = sorted(o for o in engine.registered[home_building] if roles.get(o) == "teacher")
    teacher_a, teacher_b = teacher_ids[0], teacher_ids[1]
    roster_student = rosters[teacher_a][0]
    non_roster_student = next(s for s in students_in(home_building)
                              if s not in rosters[teacher_a] and s != roster_student)
    peer_student = next(s for s in students_in(home_building)
                        if s not in (roster_student, non_roster_student))
    other_building = "building_3"
    other_dean = deans_by_building[other_building]
    cross_building_student = next(students_in(other_building))

    print("Registry: 10 deans + 100 teachers + 390 students (1+10+39 per building x 10 buildings)")
    print(f"Demo building: {home_building}  dean={dean_id}  teacher_a={teacher_a}  teacher_b={teacher_b}")
    print(f"Scenario actors: roster_student={roster_student}  non_roster_student={non_roster_student}  "
         f"peer_student={peer_student}  other_building={other_building}  other_dean={other_dean}  "
         f"cross_building_student={cross_building_student}")

    print_role_capabilities()

    print(f"\n{'=' * 78}\nSIX QUERY TYPES ON REAL DATA (Q1, Q2 -- building-wide; Q3, Q5, Q6, TRACK -- per-occupant)\n")

    # Q1, Q2: building-wide, infra-RBAC only.
    run_building_query(engine, dean_id, "Q1", home_building, after_time="09:00:00")
    run_building_query(engine, teacher_a, "Q2", home_building, at_time="12:00:00")

    # Q6: point-in-time, tiered by disclosure level.
    run_occupant_query(engine, dean_id, roster_student, "Q6", purpose="security_investigation",
                       is_office_hours=True, authorized_investigation=True, at_time=DEFAULT_AT_TIME)

    # Q3, Q5, TRACK: trajectory queries, L4-only. Self-query is the one
    # realistic way a non-dean actually holds L4, so demonstrate all three there,
    # plus the dean's authorized-investigation case for Q3/TRACK.
    run_occupant_query(engine, dean_id, roster_student, "Q3", purpose="security_investigation",
                       is_office_hours=True, authorized_investigation=True, at_time=DEFAULT_AT_TIME,
                       building_id=home_building, before_time="23:59:59")
    run_occupant_query(engine, roster_student, roster_student, "Q5", purpose="self_inspection",
                       is_office_hours=True, authorized_investigation=False, at_time=DEFAULT_AT_TIME,
                       building_id=home_building)
    run_occupant_query(engine, dean_id, roster_student, "TRACK", purpose="security_investigation",
                       is_office_hours=True, authorized_investigation=True, at_time=DEFAULT_AT_TIME)
    # Contrast: the SAME trajectory query from a Teacher, who only ever holds
    # L2 on a student -- denied outright regardless of purpose.
    run_occupant_query(engine, teacher_a, roster_student, "TRACK", purpose="academic_roster",
                       is_office_hours=True, authorized_investigation=False, at_time=DEFAULT_AT_TIME)

    print(f"\n{'=' * 78}\nHOME-BUILDING vs. CROSS-BUILDING (Dean-only Rule 2b)\n")

    # Type 1: home-building query -- any role, works normally.
    run_occupant_query(engine, teacher_a, roster_student, "Q6", purpose="academic_roster",
                       is_office_hours=True, authorized_investigation=False, at_time=DEFAULT_AT_TIME)
    # Type 2a: cross-building query BY A DEAN -- permitted (Dean is exempt).
    run_occupant_query(engine, dean_id, cross_building_student, "Q6", purpose="general_lookup",
                       is_office_hours=True, authorized_investigation=False, at_time=DEFAULT_AT_TIME)
    # Type 2b: the SAME cross-building query attempted by a non-dean -- denied,
    # proving the restriction is real and Dean-specific, not just unenforced.
    run_occupant_query(engine, teacher_a, cross_building_student, "Q6", purpose="general_lookup",
                       is_office_hours=True, authorized_investigation=False, at_time=DEFAULT_AT_TIME)
    run_occupant_query(engine, roster_student, cross_building_student, "Q6", purpose="general_lookup",
                       is_office_hours=True, authorized_investigation=False, at_time=DEFAULT_AT_TIME)
    # And a peer Dean, for completeness: Dean-to-Dean is itself cross-"building"
    # but still permitted since c_role==DEAN is the exemption, not a same-building check.
    run_occupant_query(engine, dean_id, other_dean, "Q6", purpose="admin_consultation",
                       is_office_hours=True, authorized_investigation=False, at_time=DEFAULT_AT_TIME)

    print(f"\n{'=' * 78}\nOTHER PERSONA RULES\n")
    run_occupant_query(engine, teacher_a, non_roster_student, "Q6", purpose="general_lookup",
                       is_office_hours=True, authorized_investigation=False, at_time=DEFAULT_AT_TIME)
    run_occupant_query(engine, roster_student, teacher_a, "Q6", purpose="office_hours",
                       is_office_hours=True, authorized_investigation=False, at_time=DEFAULT_AT_TIME)
    run_occupant_query(engine, roster_student, teacher_a, "Q6", purpose="office_hours",
                       is_office_hours=False, authorized_investigation=False, at_time=DEFAULT_AT_TIME)
    run_occupant_query(engine, roster_student, peer_student, "Q6", purpose="general_lookup",
                       is_office_hours=True, authorized_investigation=False, at_time=DEFAULT_AT_TIME)
    run_occupant_query(engine, roster_student, roster_student, "Q6", purpose="self_inspection",
                       is_office_hours=True, authorized_investigation=False, at_time=DEFAULT_AT_TIME)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--demo", action="store_true", help="run the full real-registry scenario battery")
    parser.add_argument("--caller", help="real occupant id of the caller")
    parser.add_argument("--target", help="real occupant id of the target (Q3/Q5/Q6/TRACK)")
    parser.add_argument("--building", help="real building id (Q1/Q2, or building_id for Q3/Q5)")
    parser.add_argument("--query", default="Q6", choices=["Q1", "Q2", "Q3", "Q5", "Q6", "TRACK"])
    parser.add_argument("--purpose", default="general_lookup", choices=[p.value for p in QueryPurpose])
    parser.add_argument("--outside-office-hours", action="store_true")
    parser.add_argument("--authorized-investigation", action="store_true")
    parser.add_argument("--at-time", default=DEFAULT_AT_TIME)
    parser.add_argument("--after-time", default="09:00:00")
    parser.add_argument("--before-time", default="23:59:59")
    args = parser.parse_args()

    clear_registry(); clear_audit_log(); clear_campus_registry()
    set_enforce_policy(True)
    try:
        if args.demo:
            run_demo()
        else:
            if not args.caller:
                parser.error("--caller is required unless --demo is given")
            roles, rosters = load_real_registry()
            engine = build_engine()
            register_real_registry(roles, rosters, engine)
            if args.query in ("Q1", "Q2"):
                if not args.building:
                    parser.error(f"{args.query} needs --building")
                kwargs = {"after_time": args.at_time} if args.query == "Q1" else {"at_time": args.at_time}
                run_building_query(engine, args.caller, args.query, args.building, **kwargs)
            else:
                if not args.target:
                    parser.error(f"{args.query} needs --target")
                run_occupant_query(engine, args.caller, args.target, args.query, purpose=args.purpose,
                                   is_office_hours=not args.outside_office_hours,
                                   authorized_investigation=args.authorized_investigation, at_time=args.at_time,
                                   building_id=args.building, before_time=args.before_time)
    finally:
        set_enforce_policy(False)
        clear_registry(); clear_audit_log(); clear_campus_registry()


if __name__ == "__main__":
    main()
